export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    games: '/dashboard/games',
    customers: '/dashboard/customers',
    admin_account: '/dashboard/admins',
    user_account: '/dashboard/users',
    bet_room: '/dashboard/rooms',
    other_room: '/dashboard/other-room',
    sessions: '/dashboard/sessions',
    session_exgame: '/dashboard/sessions-exgame',
    histories_exgame: '/dashboard/histories-exgame',
    deposit_mode: '/dashboard/deposit-mode',
    deposits: '/dashboard/deposits',
    user_deposit_withdraw: '/dashboard/users/deposit-withdraw',
    user_bet_history: '/dashboard/users/bet-history',
    auto_deposits: '/dashboard/auto-deposit',
    withdraws: '/dashboard/withdraws',
    bank: '/dashboard/bank',
    posts: '/dashboard/posts',
    supports: '/dashboard/supports',
    banners: '/dashboard/banners',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
